# Generated by Django 4.0.5 on 2022-07-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineJudge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_input',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output',
            field=models.CharField(default='', max_length=300),
        ),
    ]
