# Generated by Django 4.0.5 on 2022-07-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineJudge', '0004_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='sample_input',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_output',
        ),
    ]
